### ISSUE TITLE
GitHub release draft issues  and how to automate github release

### ISSUE THREAD

**Issue by dasd412** [dasd412/RemakeDiabetesDiaryAPI#55]

**Comment by dasd412** [comment]
검색 및 테스트해보니 master branch에 push가 아니라, PR 및 merge를 해야만 release draft가 자동 작성되는 것이 확인되었다. 

참고 자료
https://github.com/release-drafter/release-drafter

**Comment by dasd412** [comment]
하지만 아직 config 파일을 읽어서 draft가 작성되고 있지 않다.

**Comment by dasd412** [comment]
원인을 알았다. 
바로 templates 태그 다음에 `|`를 작성해야 하는데 누락되었기 때문이다.

아래는 공식 repo에서 발췌한 config yml이다.
잘 보면 `template: | ` 이라고 기재되어 있었다.

```
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  $CHANGES
```
